/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RootOldRouteImport } from './routes/_root.old'
import { Route as AuthenticatedSymptomsRouteImport } from './routes/_authenticated/symptoms'
import { Route as AuthenticatedRemediesRouteImport } from './routes/_authenticated/remedies'
import { Route as AuthenticatedMedicineRouteImport } from './routes/_authenticated/medicine'
import { Route as AuthenticatedInteractionsRouteImport } from './routes/_authenticated/interactions'
import { Route as AuthenticatedDietRouteImport } from './routes/_authenticated/diet'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RootOldRoute = RootOldRouteImport.update({
  id: '/_root/old',
  path: '/old',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSymptomsRoute = AuthenticatedSymptomsRouteImport.update({
  id: '/symptoms',
  path: '/symptoms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRemediesRoute = AuthenticatedRemediesRouteImport.update({
  id: '/remedies',
  path: '/remedies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMedicineRoute = AuthenticatedMedicineRouteImport.update({
  id: '/medicine',
  path: '/medicine',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInteractionsRoute =
  AuthenticatedInteractionsRouteImport.update({
    id: '/interactions',
    path: '/interactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDietRoute = AuthenticatedDietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diet': typeof AuthenticatedDietRoute
  '/interactions': typeof AuthenticatedInteractionsRoute
  '/medicine': typeof AuthenticatedMedicineRoute
  '/remedies': typeof AuthenticatedRemediesRoute
  '/symptoms': typeof AuthenticatedSymptomsRoute
  '/old': typeof RootOldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/diet': typeof AuthenticatedDietRoute
  '/interactions': typeof AuthenticatedInteractionsRoute
  '/medicine': typeof AuthenticatedMedicineRoute
  '/remedies': typeof AuthenticatedRemediesRoute
  '/symptoms': typeof AuthenticatedSymptomsRoute
  '/old': typeof RootOldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/diet': typeof AuthenticatedDietRoute
  '/_authenticated/interactions': typeof AuthenticatedInteractionsRoute
  '/_authenticated/medicine': typeof AuthenticatedMedicineRoute
  '/_authenticated/remedies': typeof AuthenticatedRemediesRoute
  '/_authenticated/symptoms': typeof AuthenticatedSymptomsRoute
  '/_root/old': typeof RootOldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/diet'
    | '/interactions'
    | '/medicine'
    | '/remedies'
    | '/symptoms'
    | '/old'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/diet'
    | '/interactions'
    | '/medicine'
    | '/remedies'
    | '/symptoms'
    | '/old'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/diet'
    | '/_authenticated/interactions'
    | '/_authenticated/medicine'
    | '/_authenticated/remedies'
    | '/_authenticated/symptoms'
    | '/_root/old'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  RootOldRoute: typeof RootOldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_root/old': {
      id: '/_root/old'
      path: '/old'
      fullPath: '/old'
      preLoaderRoute: typeof RootOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/symptoms': {
      id: '/_authenticated/symptoms'
      path: '/symptoms'
      fullPath: '/symptoms'
      preLoaderRoute: typeof AuthenticatedSymptomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/remedies': {
      id: '/_authenticated/remedies'
      path: '/remedies'
      fullPath: '/remedies'
      preLoaderRoute: typeof AuthenticatedRemediesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/medicine': {
      id: '/_authenticated/medicine'
      path: '/medicine'
      fullPath: '/medicine'
      preLoaderRoute: typeof AuthenticatedMedicineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/interactions': {
      id: '/_authenticated/interactions'
      path: '/interactions'
      fullPath: '/interactions'
      preLoaderRoute: typeof AuthenticatedInteractionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/diet': {
      id: '/_authenticated/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof AuthenticatedDietRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDietRoute: typeof AuthenticatedDietRoute
  AuthenticatedInteractionsRoute: typeof AuthenticatedInteractionsRoute
  AuthenticatedMedicineRoute: typeof AuthenticatedMedicineRoute
  AuthenticatedRemediesRoute: typeof AuthenticatedRemediesRoute
  AuthenticatedSymptomsRoute: typeof AuthenticatedSymptomsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDietRoute: AuthenticatedDietRoute,
  AuthenticatedInteractionsRoute: AuthenticatedInteractionsRoute,
  AuthenticatedMedicineRoute: AuthenticatedMedicineRoute,
  AuthenticatedRemediesRoute: AuthenticatedRemediesRoute,
  AuthenticatedSymptomsRoute: AuthenticatedSymptomsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  RootOldRoute: RootOldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
